### ISSUE TITLE
set custom If-None-Match header

### ISSUE THREAD

**Issue by davekaro** [benedikt/layer-ruby#20]
After reading over https://developer.layer.com/docs/platform/introduction#deduplication, I'm not sure I understand the point of the current behavior here https://github.com/benedikt/layer-ruby/blob/ce7c76eaf61b5e92f4a38172e739d8d9a4932ede/lib/layer/client.rb#L72 for setting the If-None-Match header. As it is now, every request would generate a new uuid, making de-duplication on Layer's end impossible.

Instead, I should be able to send the If-None-Match header per request in order to avoid potential duplication. If that makes sense, I'd be willing to open a PR.

**Comment by benedikt** [comment]
Hi @davekaro,

thanks for bringing this up. The current behavior does indeed generate a new uuid on every request. It's possible to provide your own `If-None-Match` header to the client, though. Unfortunately, right now this only works when you're using the client directly.

I initially added this header so that some proxy server somewhere in between could in theory redo the request without it getting duplicated. To be honest, that's a very unlikely most of the times :-)

I'd be happy to add improved support for the de-duplication feature into this gem. However, right now I'm not sure about a good API for this. I'd love to hear your thoughts on this. 

Cheers,

Benedikt

**Comment by davekaro** [comment]
I just tried exposing the headers arg in the create operation. See https://github.com/davekaro/layer-ruby/commit/6f4ed4ae964c26cb2e39df39a90765b4991bd640

It does change the API though. Perhaps it would be better to just use the client directly in cases where you want to set the `If-None-Match`.

**Comment by benedikt** [comment]
I'd agree that it's probably the best just to use the client directly.
